export const site = {
  name: "Clinton Brown",
  /** How I introduce myself. Also the phrase roles are posted under. */
  role: "Shopify & headless commerce engineer",
  /** The formal title, kept for metadata and the résumé. */
  title: "Senior E-Commerce Full Stack Developer",
  location: "Murfreesboro, TN",
  availability: "Open to remote",
  email: "cbdev777@outlook.com",
  github: "https://github.com/Seedh0922",
  linkedin: "https://www.linkedin.com/in/clinton-brown-72210b426",
  url: "https://clintonbrown.vercel.app",
  summary:
    "Thirteen years building for the web, eight of them on Shopify and Shopify Plus.",

  /**
   * Optional assets. Both render only when set, so nothing on the site can ship
   * as a broken link or a missing image — the two things a reviewer notices
   * fastest. Drop the file in `public/` and fill the path in.
   */
  resumePdf: null as string | null, // e.g. "/clinton-brown-resume.pdf"
  photo: null as string | null, // e.g. "/clinton-brown.jpg"
} as const;

/**
 * Featured work. Convention is two to four, each with a live link, source, and
 * a written case study; `live: null` simply hides that button rather than
 * shipping a dead one.
 */
export type Project = {
  slug: string;
  name: string;
  kicker: string;
  blurb: string;
  results: { value: string; label: string }[];
  stack: string[];
  image: string | null;
  imageAlt: string;
  live: string | null;
  code: string | null;
  caseStudy: string | null;
  status?: "in-progress";
};

export const projects: Project[] = [
  {
    slug: "shopify-headless-perf-lab",
    name: "Shopify Headless Perf Lab",
    kicker: "Headless storefront · Open source",
    blurb:
      "A headless Shopify storefront on Hydrogen and the Oxygen worker runtime, built so its performance numbers can be regenerated by anyone who clones it. The same storefront ships in two modes — one tuned, one carrying six regressions app-heavy themes commonly pick up — and one script measures both. Lighthouse budgets run on every pull request.",
    results: [
      { value: "−47%", label: "Largest Contentful Paint" },
      { value: "143 → 4 ms", label: "Total Blocking Time" },
      { value: "−34%", label: "Transfer size" },
    ],
    stack: [
      "Hydrogen",
      "React Router 7",
      "TypeScript",
      "Storefront API",
      "Lighthouse CI",
      "GitHub Actions",
    ],
    image: "/work/perf-lab.webp",
    imageAlt:
      "The storefront homepage: a full-width hero image of running shoes above a four-product recommended grid.",
    live: null,
    code: "https://github.com/Seedh0922/shopify-headless-perf-lab",
    caseStudy: "/work/shopify-headless-perf-lab",
  },
  {
    slug: "shopify-inventory-sync-lab",
    name: "Shopify Inventory Sync Lab",
    kicker: "Integration service · Open source",
    blurb:
      "Shopify redelivers webhooks until it gets a 2xx and does not promise they arrive in order. The stock level has to be right anyway. The same job is implemented twice — a counter that each delivery mutates, and a ledger that derives the quantity from the set of events observed — and one command replays a mangled feed through both.",
    results: [
      { value: "0 units", label: "Ledger drift across six seeds" },
      { value: "19 / 25", label: "SKUs a mutable counter gets wrong" },
      { value: "339", label: "Repeat deliveries absorbed" },
    ],
    stack: [
      "Node.js",
      "TypeScript",
      "Next.js",
      "Shopify webhooks",
      "HMAC",
      "GitHub Actions",
    ],
    image: "/work/sync-lab.webp",
    imageAlt:
      "The dashboard: a feed of 1,363 deliveries for 1,024 real movements, with the naive projection marked drifted and the ledger marked exact.",
    live: "https://shopify-inventory-sync-lab.vercel.app",
    code: "https://github.com/Seedh0922/shopify-inventory-sync-lab",
    caseStudy: null,
  },
];

/**
 * Kept deliberately short. A list of forty technologies makes none of them
 * credible; the full inventory lives on the résumé.
 */
export const stack = [
  {
    group: "Commerce",
    items: [
      "Shopify Plus",
      "Hydrogen",
      "Storefront API",
      "Admin API",
      "Liquid",
      "Checkout Extensibility",
    ],
  },
  {
    group: "Front end",
    items: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
  },
  {
    group: "Back end",
    items: ["Node.js", "GraphQL", "PostgreSQL", "MySQL", "Laravel"],
  },
  {
    group: "Delivery & measurement",
    items: ["GitHub Actions", "Vercel", "Docker", "Lighthouse CI", "GA4"],
  },
] as const;

/**
 * What I do, each backed by work I have actually shipped. This is the part of
 * the site that carries the breadth; the case studies carry the depth.
 */
export const practice = [
  {
    heading: "Storefronts",
    body: "Liquid themes and headless front ends on Next.js and Hydrogen. Online Store 2.0 sections, metafield content models, Shopify Markets locale routing, and the SEO checklist that keeps redirects and canonicals intact through a replatform.",
    proof:
      "Led a headless migration to Next.js and the Storefront API for a DTC brand, phased so navigation and catalog landed before higher-risk PDP work.",
  },
  {
    heading: "Apps & APIs",
    body: "Custom apps on the Admin and Storefront APIs, GraphQL, webhooks, app proxies, Checkout Extensibility and Theme App Extensions — for the promotion, account and catalog logic that does not fit cleanly in theme code.",
    proof:
      "Built merchant-specific apps across Shopify Plus accounts, and rebuilt three Plus themes around reusable sections and metafields so marketers could launch campaigns without a theme deploy.",
  },
  {
    heading: "Integrations",
    body: "Node.js services connecting Shopify to ERP, warehouse, payment and CRM systems: catalog and inventory sync, order export, webhook handling with retries and alerting when a handoff fails.",
    proof:
      "Built an ERP catalog and inventory sync into Shopify with retry logic for failed updates, and wired Stripe, PayPal and ShipStation order flows for Plus merchants.",
  },
  {
    heading: "Performance & growth",
    body: "Core Web Vitals, technical SEO, GA4 and GTM event integrity, Klaviyo flows, A/B testing and CRO — measured before and after, with budgets in CI so a regression is caught at review time.",
    proof:
      "Brought PDP and collection LCP down ~22%, lifted mobile Lighthouse on priority templates from the low 40s into the mid-70s, and ran the CRO tests behind a ~6% lift in checkout-start rate.",
  },
] as const;

export const repo = {
  url: "https://github.com/Seedh0922/shopify-headless-perf-lab",
  report:
    "https://github.com/Seedh0922/shopify-headless-perf-lab/blob/main/docs/perf/latest.md",
  levers:
    "https://github.com/Seedh0922/shopify-headless-perf-lab/blob/main/app/lib/perf-mode.ts",
  budgets:
    "https://github.com/Seedh0922/shopify-headless-perf-lab/blob/main/lighthouserc.json",
  adr: "https://github.com/Seedh0922/shopify-headless-perf-lab/tree/main/docs/adr",
  // Set once the demonstration pull request is open.
  failingPr: "https://github.com/Seedh0922/shopify-headless-perf-lab/pull/1",
} as const;

/**
 * Homepage figures from docs/perf/latest.md — mobile, applied throttling at
 * 4x CPU on Slow 4G, median of three runs. Lower is better for every metric
 * listed here, which is what lets them share one visual direction.
 */
export type Metric = {
  label: string;
  unit: string;
  baseline: number;
  optimized: number;
  /** Formatted for display; keeps the thousands separators explicit. */
  baselineText: string;
  optimizedText: string;
  changeText: string;
  improved: boolean;
};

export const metrics: Metric[] = [
  {
    label: "Largest Contentful Paint",
    unit: "ms",
    baseline: 4968,
    optimized: 2650,
    baselineText: "4,968 ms",
    optimizedText: "2,650 ms",
    changeText: "−47%",
    improved: true,
  },
  {
    label: "Total Blocking Time",
    unit: "ms",
    baseline: 143,
    optimized: 4,
    baselineText: "143 ms",
    optimizedText: "4 ms",
    changeText: "−97%",
    improved: true,
  },
  {
    label: "Speed Index",
    unit: "ms",
    baseline: 5010,
    optimized: 3088,
    baselineText: "5,010 ms",
    optimizedText: "3,088 ms",
    changeText: "−38%",
    improved: true,
  },
  {
    label: "Transfer size",
    unit: "KB",
    baseline: 714,
    optimized: 473,
    baselineText: "714 KB",
    optimizedText: "473 KB",
    changeText: "−34%",
    improved: true,
  },
];

export const headline = [
  {
    label: "Largest Contentful Paint",
    value: "2,650 ms",
    delta: "−47% vs baseline",
    note: "from 4,968 ms",
  },
  {
    label: "Total Blocking Time",
    value: "4 ms",
    delta: "−97% vs baseline",
    note: "from 143 ms",
  },
  {
    label: "Lighthouse performance",
    value: "95",
    delta: "+19 points",
    note: "from 76",
  },
] as const;

export const levers = [
  {
    lever: "CDN preconnect",
    optimized: "present",
    baseline: "removed",
    why: "A TLS round trip before the LCP image can start",
  },
  {
    lever: "Hero image",
    optimized: "eager + high priority",
    baseline: "lazy + auto",
    why: "Lazy-loading the LCP element defeats the preload scanner",
  },
  {
    lever: "sizes hint",
    optimized: "viewport-aware",
    baseline: "hardcoded 1600px",
    why: "Mobile downloads a desktop-width image",
  },
  {
    lever: "Layout reservation",
    optimized: "aspect ratio set",
    baseline: "absent",
    why: "The usual cause of a bad CLS score",
  },
  {
    lever: "Third-party app script",
    optimized: "absent",
    baseline: "synchronous in <head>",
    why: "Reviews / popup / upsell bundles — the biggest real-world cost",
  },
  {
    lever: "Storefront API cache",
    optimized: "CacheLong / CacheShort",
    baseline: "CacheNone",
    why: "Warm vs cold TTFB",
  },
] as const;

export const budgets = [
  { assertion: "Performance category", threshold: "≥ 0.90", level: "error" },
  { assertion: "Accessibility category", threshold: "≥ 0.95", level: "error" },
  { assertion: "SEO category", threshold: "≥ 0.95", level: "error" },
  { assertion: "Largest Contentful Paint", threshold: "≤ 2,500 ms", level: "error" },
  { assertion: "Cumulative Layout Shift", threshold: "≤ 0.10", level: "error" },
  { assertion: "Total Blocking Time", threshold: "≤ 300 ms", level: "error" },
  { assertion: "Unsized images", threshold: "none", level: "error" },
] as const;

export const roles = [
  {
    when: "Dec 2025 — Jun 2026",
    title: "Senior E-Commerce Full Stack Developer",
    org: "Netalico · Remote",
    note: "Owned day-to-day Shopify Plus delivery across merchant accounts — Checkout Extensibility, custom apps on the Admin and Storefront APIs, and a Node.js service syncing ERP catalog and inventory into Shopify with webhook handling and retry logic. Brought PDP and collection LCP down ~22%.",
  },
  {
    when: "Jan 2024 — Nov 2025",
    title: "Senior Ecommerce Engineer",
    org: "Human Good Kind · Nashville, TN",
    note: "Led a headless migration to Next.js and the Shopify Storefront API for a DTC brand, phased so navigation and catalog landed before higher-risk PDP work. Checkout stayed on Shopify. Email-attributed revenue rose ~14% over two quarters; a shipping-message test lifted checkout-start ~6%.",
  },
  {
    when: "Dec 2022 — Dec 2023",
    title: "Senior Full Stack Engineer",
    org: "Acklen Avenue · Nashville, TN",
    note: "React/Next.js clients and Node.js services for enterprise SaaS. Tuned PostgreSQL schemas and indexes on the heaviest report path, taking response time from ~4.5 s to under 900 ms.",
  },
  {
    when: "Oct 2019 — Nov 2022",
    title: "Senior Shopify Developer",
    org: "UPQODE · Nashville, TN",
    note: "Shopify and Shopify Plus builds for retail, CPG and subscription merchants. Rebuilt three Plus themes around reusable Liquid sections and metafields so marketers could launch without theme deploys. Mobile Lighthouse on priority templates went from the low 40s into the mid-70s.",
  },
  {
    when: "Jan 2017 — Sep 2019",
    title: "Full Stack Developer",
    org: "RH Consulting LLC · Murfreesboro, TN",
    note: "React front ends with Node.js and Laravel/PHP back ends; REST services connecting Shopify and WooCommerce stores to Stripe, PayPal and inventory/CRM systems.",
  },
  {
    when: "Jun 2013 — Dec 2016",
    title: "Junior Frontend Developer",
    org: "Raine Digital · Murfreesboro, TN",
    note: "Responsive layouts and WordPress theme work for marketing sites and early ecommerce projects.",
  },
] as const;

export const capabilities = [
  {
    heading: "Commerce platforms",
    body: "Shopify, Shopify Plus, Hydrogen, headless commerce, WooCommerce, BigCommerce, Shopify Markets",
  },
  {
    heading: "Shopify surface",
    body: "Liquid, Admin API, Storefront API, custom apps, webhooks, Checkout Extensibility, Theme App Extensions, metafields",
  },
  {
    heading: "Front end",
    body: "React, Next.js, TypeScript, Vue.js, Tailwind CSS, Redux, React Query, responsive and accessible UI",
  },
  {
    heading: "Back end & data",
    body: "Node.js, Express, Laravel/PHP, GraphQL, REST, MySQL, PostgreSQL, MongoDB, Redis",
  },
  {
    heading: "Delivery",
    body: "GitHub Actions, Azure DevOps, Docker, AWS, Vercel, Cloudflare, CI/CD, Lighthouse CI budgets",
  },
  {
    heading: "Growth & measurement",
    body: "Core Web Vitals, technical SEO, GA4, GTM, Search Console, Klaviyo, Hotjar, A/B testing, CRO",
  },
] as const;
